version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo -e '@neverendingsupport:registry=https://registry.nes.herodevs.com/npm/pkg/\n//registry.nes.herodevs.com/npm/pkg/:_authToken="'${NES_AUTH_TOKEN}'"' > .npmrc
      - npm install --legacy-peer-deps

  pre_build:
    commands:
      - chmod 755 ./scripts/*.sh
      - ./scripts/code_pipeline/pre_build_phase.sh

  build:
    commands:
      - npm run build-vue

  post_build:
    commands:
      - ./scripts/code_pipeline/post_build_phase.sh

artifacts:
  files:
  - '.ebextensions/**/*'
  - '.platform/**/*'
  - 'Procfile'
  - 'application.py'
  - 'app/**/*'
  - 'boac/**/*'
  - 'config/**/*'
  - 'consoler.py'
  - 'dist/**/*'
  - 'fixtures/**/*'
  - 'requirements.txt'
  - 'scripts/**/*'
